name: Rust Format & Test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
    branches: [main, development]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    if: "! github.event.pull_request.draft"
    uses: ./.github/workflows/build.yml
    with:
      upload-binary: true

  format-and-test:
    name: Run Rust Tests
    if: "! github.event.pull_request.draft"
    uses: ./.github/workflows/_pr-checks.yml
    with:
      apt-deps: pkg-config
